### ISSUE TITLE
NullReferenceException with tileOverlay.ShowWindow() in provided sample scene

### ISSUE THREAD

**Issue by BradFitz66** [FreshlyBrewedCode/unity-mesh-tilesets#2]
Upon attempting to do anything on in the sample scene, I get a NullReferenceException when selecting a tileset.

> NullReferenceException: Object reference not set to an instance of an object
> MeshTilesetsEditor.TilesetRendererEditor.OnSceneGUI () (at Assets/unity-mesh-tilesets-1.0.3/Assets/Mesh Tilesets/Editor/TilesetRendererEditor.cs:173)
> System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <fb001e01371b4adca20013e0ac763896>:0)
> Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
> System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <fb001e01371b4adca20013e0ac763896>:0)
> System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <fb001e01371b4adca20013e0ac763896>:0)
> UnityEditor.SceneView.CallOnSceneGUI () (at <a0a9ad37e16b4f7cb955e1101b72d4cc>:0)
> UnityEditor.SceneView.HandleSelectionAndOnSceneGUI () (at <a0a9ad37e16b4f7cb955e1101b72d4cc>:0)
> UnityEditor.SceneView.OnGUI () (at <a0a9ad37e16b4f7cb955e1101b72d4cc>:0)
> System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <fb001e01371b4adca20013e0ac763896>:0)
> Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
> System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <fb001e01371b4adca20013e0ac763896>:0)
> System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <fb001e01371b4adca20013e0ac763896>:0)
> UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at <a0a9ad37e16b4f7cb955e1101b72d4cc>:0)
> UnityEditor.HostView.Invoke (System.String methodName) (at <a0a9ad37e16b4f7cb955e1101b72d4cc>:0)
> UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <a0a9ad37e16b4f7cb955e1101b72d4cc>:0)
> UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <a0a9ad37e16b4f7cb955e1101b72d4cc>:0)
> UnityEditor.DockArea.OldOnGUI () (at <a0a9ad37e16b4f7cb955e1101b72d4cc>:0)
> UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <78b213560771414e9fa6f1b95f5ad8bb>:0)
> UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <78b213560771414e9fa6f1b95f5ad8bb>:0)
> UnityEngine.UIElements.IMGUIContainer.DoIMGUIRepaint () (at <78b213560771414e9fa6f1b95f5ad8bb>:0)
> UnityEngine.UIElements.UIR.RenderChainCommand.ExecuteNonDrawMesh (UnityEngine.UIElements.UIR.DrawParams drawParams, System.Boolean straightY, System.Single pixelsPerPoint, System.Exception& immediateException) (at <78b213560771414e9fa6f1b95f5ad8bb>:0)
> Rethrow as ImmediateModeException
> UnityEngine.UIElements.UIR.RenderChain.Render (UnityEngine.Rect viewport, UnityEngine.Matrix4x4 projection, UnityEngine.UIElements.PanelClearFlags clearFlags) (at <78b213560771414e9fa6f1b95f5ad8bb>:0)
> UnityEngine.UIElements.UIRRepaintUpdater.DrawChain (UnityEngine.Rect viewport, UnityEngine.Matrix4x4 projection) (at <78b213560771414e9fa6f1b95f5ad8bb>:0)
> UnityEngine.UIElements.UIRRepaintUpdater.Update () (at <78b213560771414e9fa6f1b95f5ad8bb>:0)
> UnityEngine.UIElements.VisualTreeUpdater.UpdateVisualTreePhase (UnityEngine.UIElements.VisualTreeUpdatePhase phase) (at <78b213560771414e9fa6f1b95f5ad8bb>:0)
> UnityEngine.UIElements.Panel.UpdateForRepaint () (at <78b213560771414e9fa6f1b95f5ad8bb>:0)
> UnityEngine.UIElements.Panel.Repaint (UnityEngine.Event e) (at <78b213560771414e9fa6f1b95f5ad8bb>:0)
> UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <78b213560771414e9fa6f1b95f5ad8bb>:0)
> UnityEngine.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <78b213560771414e9fa6f1b95f5ad8bb>:0)
> UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <819de1aa368e45faa4f78e26c97c62b0>:0)

which goes to this line

`tileOverlay.ShowWindow();`

**Comment by FreshlyBrewedCode** [comment]
Hi, thanks for the report. Could you specify which version of Unity you are using? Also, are you on PC or Mac? Thanks!

**Comment by FreshlyBrewedCode** [comment]
@BradFitz66 I added a fix to make the tile overlay window work in Unity 2019. I assume this was the cause of the `NullReferenceException` you encountered. I would appreciate if you could update to version 1.0.4 and see if the problem is solved. If not feel free to reopen the issue.
